customer_name = input("What your name?")
print("Hello "+ customer_name)
customer_age = input("How old are you ?")
print("ok Fine, Lets give your address where we need to deliver percel")
customer_address = input()
print("All thinks are done. We will sent a confermation sms")